### ISSUE TITLE
Collection: splunk.es, module: splunk_correlation_searches - Unable to skip custom annotation configuration

### ISSUE THREAD

**Issue by CISCO-SWITCH-74** [ansible-collections/splunk.es#77]
##### SUMMARY
Not able to set a null value in custom annotation section using splunk_correlation_searches module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
splunk_correlation_searches

##### ANSIBLE VERSION
Ansible 2.15

##### COLLECTION VERSION
splunk.es  4.0.0 

##### STEPS TO REPRODUCE
I tried different way to skip the custom annotations :

```
- name: Create a new CS
  splunk.es.splunk_correlation_searches:
    config:
    - annotations:
        cis20: null
        custom: null
        kill_chain_phases: null
        mitre_attack:
        - T1048
        - T1049
        nist: null
      app: SplunkEnterpriseSecuritySuite
      cron_schedule: 1 * * * *
      disabled: true
      name: Test CS
      schedule_priority: default
      schedule_window: auto
      scheduling: continuous
      search: 'index=test | stats count by test'
      suppress_alerts: true
      throttle_fields_to_group_by:
      - test
      throttle_window_duration: 14400s
      time_earliest: -24h
      time_latest: now
      trigger_alert: once
      trigger_alert_when: number of events
      trigger_alert_when_condition: greater than
      trigger_alert_when_value: '0'
      ui_dispatch_context: SplunkEnterpriseSecuritySuite
    state: merged
```

```
- name: Create a new CS
  splunk.es.splunk_correlation_searches:
    config:
    - annotations:
        cis20: null
        custom:
          - framework: null
            custom_annotations: null
        kill_chain_phases: null
        mitre_attack:
        - T1048
        - T1049
        nist: null
      app: SplunkEnterpriseSecuritySuite
      cron_schedule: 1 * * * *
      disabled: true
      name: Test CS
      schedule_priority: default
      schedule_window: auto
      scheduling: continuous
      search: 'index=test | stats count by test'
      suppress_alerts: true
      throttle_fields_to_group_by:
      - test
      throttle_window_duration: 14400s
      time_earliest: -24h
      time_latest: now
      trigger_alert: once
      trigger_alert_when: number of events
      trigger_alert_when_condition: greater than
      trigger_alert_when_value: '0'
      ui_dispatch_context: SplunkEnterpriseSecuritySuite
    state: merged
```

##### EXPECTED RESULTS
Create a CS without custom annotations. It is possible using the Splunk web interface.

##### ACTUAL RESULTS
first test gives error :

```
fatal: [server01]: FAILED! => {
    "msg": "Unexpected failure during module execution: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)",
    "stdout": ""
}
```

the second playbook gives :

```
fatal: [server01]: FAILED! => {
    "msg": "Unexpected failure during module execution: 'custom_annotations'",
    "stdout": ""
}
```
